apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # "prometheus" = nom du service Compose, résolu sur le réseau interne.
    url: http://prometheus:9090
    isDefault: true
    editable: true
